[tox]
min_version = 4.26
envlist =
    py{312,313,314}-cl{817}-lts{1}-nx{342}-nltk{391}-np{224}-oai{234}-pd{223}-pw{149}-pj{5168}-rich{1394}-toml{0102}

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
usedevelop = True
commands = pytest tests --dist loadscope {posargs}
deps =
    cl817: click>=8.1.7,<9
    c4ai063: crawl4ai>=0.6.3,<0.7
    lts1: langchain-text-splitters>=1.0.0,<2
    nx342: networkx>=3.4.2,<4
    nltk391: nltk>=3.9.1,<4
    np224: numpy>=2.2.4
    oai234: openai>=2.34.0
    pd223: pandas>=2.2.3,<3
    pw149: playwright>=1.49.0,<1.52
    pj5168: pyjson5>=1.6.8,<2
    rich1394: rich>=13.9.4,<14
    toml0102: toml>=0.10.2,<0.11
    pytest>=8.0
extras =
    test
setenv =
    GITHUB_ACTIONS = true

[testenv:msv]
usedevelop = True
description = minimum supported versions
deps=
    click~=8.1.7
    crawl4ai~=0.6.3
    langchain-text-splitters~=1.0.0
    networkx~=3.4.2
    nltk~=3.9.1
    numpy>=2.2.4
    openai~=2.34.0
    pandas~=2.2.3
    playwright~=1.49.0
    pyjson5~=1.6.8
    rich~=13.9.4
    toml~=0.10.2
    pytest>=8.0

[testenv:latest]
description = (almost) no constraints, thus latest version of dependencies
deps=
    crawl4ai<=0.72.0
