name: Codecov

on:
  push:
    branches: [main]
    paths:
      - compass/**
      - tests/**
      - .github/workflows/codecov.yml
      - pyproject.toml
      - pixi.lock
  pull_request:
    paths:
      - compass/**
      - tests/**
      - .github/workflows/codecov.yml
      - pyproject.toml
      - pixi.lock
  workflow_dispatch:

jobs:
  run:
    name: Codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
      with:
        pixi-version: v0.68.1
        locked: true
        cache: true
        cache-write: false
        environments: pdev

    - name: Generate coverage report
      run: |
        pixi reinstall -e pdev --locked INFRA-COMPASS
        pixi run -e pdev --locked tests-p

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
